# Generated by Django 5.0 on 2024-01-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=100)),
                ('socialaccount1', models.CharField(max_length=50)),
                ('socialaccount2', models.CharField(max_length=50)),
                ('socialaccount3', models.CharField(max_length=50)),
            ],
        ),
    ]
