# Generated by Django 5.0 on 2024-01-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_uploading'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploading',
            name='file',
            field=models.FileField(default=None, upload_to='<django.db.models.fields.CharField>/'),
        ),
    ]
