# Generated by Django 5.0 on 2024-01-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_uploading_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploading',
            name='file',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
