# Generated by Django 5.0 on 2024-01-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_uploading_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploading',
            name='file',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='file/'),
        ),
    ]
